### ISSUE TITLE
Script spews InsecureRequestWarning on run

### ISSUE THREAD

**Issue by mikedesu** [ghostlulzhacks/waybackSqliScanner#1]
$ time python3 main.py website.com
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
return self._lock.__enter__()
KeyboardInterrupt

real    0m4.108s
user    0m2.047s
sys     0m0.416s

$ uname -a
Linux recon0 5.0.0-15-generic #16-Ubuntu SMP Mon May 6 17:41:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by IfrahIman** [comment]
Same issue!

**Comment by renekroka** [comment]
Same issue here

**Comment by ghostlulzbishop** [comment]
Yeah its because because im not verifying the SSL cert. Ill add a fix today.

**Comment by ghostlulzhacks** [comment]
Yeah its because im not verifying the SSL cert. The problem has been fixed and you shouldnt see those warning anymore.
